apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex-server 
  labels:
    name: plex-server 
spec:
  replicas: 1
  selector:
    matchLabels:
      name: plex-server 
  template:
    metadata:
      labels:
        name: plex-server 
    spec:
      hostNetwork: true
      volumes:
      - hostPath:
          path: /volumes/plex-config 
        name: config 
      - hostPath:
          path: /mnt/disks/library/videos
        name: movies1
      - hostPath:
          path: /mnt/disks/library/tvseries
        name: tv1
      containers:
      - name: plex-server 
        image: plexinc/pms-docker 
        imagePullPolicy: IfNotPresent
        livenessProbe:
          tcpSocket:
            port: 32400 
          initialDelaySeconds: 60
          periodSeconds: 5
        volumeMounts:
        - mountPath: /config
          name: config 
        - mountPath: /movies1 
          name: movies1
        - mountPath: /tv1
          name: tv1
        env:
        - name: PUID 
          value: "1000"
        - name: PGID 
          value: "4000"
        - name: VERSION 
          value: "docker"
        - name: UMASK_SET 
          value: "022"
        - name: TZ
          value: "America/Los_Angeles"
